//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalCMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalCMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BEEP {
            get {
                return ResourceManager.GetStream("BEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;layout height=&quot;300&quot; width=&quot;0&quot; vtype=&quot;fixed&quot; top=&quot;0&quot; left=&quot;0&quot; vpos=&quot;bottom&quot; hpos=&quot;center&quot; margin=&quot;80,15,80,15&quot; bgcolor=&quot;#ffffff&quot; btncolor=&quot;#52514e&quot; btntxtcolor=&quot;#ffffff&quot; capscolor=&quot;#e31102&quot; shiftcolor=&quot;#0b56b8&quot; enterkey=&quot;enter&quot;&gt;
        ///  &lt;row&gt;
        ///    &lt;key code=&quot;HASH&quot; text=&quot;#&quot; shtext=&quot;~&quot; /&gt;
        ///    &lt;key code=&quot;1&quot; text=&quot;1&quot; shtext=&quot;!&quot; /&gt;
        ///    &lt;key code=&quot;2&quot; text=&quot;2&quot; shtext=&quot;&amp;quot;&quot; /&gt;
        ///    &lt;key code=&quot;3&quot; text=&quot;3&quot; shtext=&quot;£&quot; /&gt;
        ///    &lt;key code=&quot;4&quot; text=&quot;4&quot; shtext=&quot;$&quot; /&gt;
        ///    &lt;key code=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_ANTENNA32 {
            get {
                object obj = ResourceManager.GetObject("ICO_ANTENNA32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_ANTENNA64 {
            get {
                object obj = ResourceManager.GetObject("ICO_ANTENNA64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_SERIAL32 {
            get {
                object obj = ResourceManager.GetObject("ICO_SERIAL32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_SERIAL64 {
            get {
                object obj = ResourceManager.GetObject("ICO_SERIAL64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_TEMP32 {
            get {
                object obj = ResourceManager.GetObject("ICO_TEMP32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_TEMP64 {
            get {
                object obj = ResourceManager.GetObject("ICO_TEMP64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_TOUCHSCREEN32 {
            get {
                object obj = ResourceManager.GetObject("ICO_TOUCHSCREEN32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_TOUCHSCREEN64 {
            get {
                object obj = ResourceManager.GetObject("ICO_TOUCHSCREEN64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_USB_MODEM32 {
            get {
                object obj = ResourceManager.GetObject("ICO_USB_MODEM32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_USB_MODEM64 {
            get {
                object obj = ResourceManager.GetObject("ICO_USB_MODEM64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_USB32 {
            get {
                object obj = ResourceManager.GetObject("ICO_USB32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_USB64 {
            get {
                object obj = ResourceManager.GetObject("ICO_USB64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_WIFI32 {
            get {
                object obj = ResourceManager.GetObject("ICO_WIFI32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_WIFI64 {
            get {
                object obj = ResourceManager.GetObject("ICO_WIFI64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OMRON_X64_CAT {
            get {
                object obj = ResourceManager.GetObject("OMRON_X64_CAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Windows Vista setup File
        ///;
        ///; $Id: WinVistaCom.inf,v 1.4 2010/07/28 10:49:49 k-hayakawa Exp $
        ///;
        ///
        ///[Version] 
        ///LayoutFile=layout.inf
        ///Signature=&quot;$Windows NT$&quot; 
        ///Class=Ports 
        ///ClassGuid={4D36E978-E325-11CE-BFC1-08002BE10318} 
        ///
        ///Provider=%OMRON% 
        ///DriverVer=11/22/2016,3.0.0.1 
        ///CatalogFile=HVC-P2_Win64.cat
        ///
        ///[Manufacturer] 
        ///%OMRON%=OMRON,NTamd64 
        ///
        ///[OMRON.NTamd64] 
        ///%OMRON_CDC%=Reader, USB\VID_0590&amp;PID_00CA
        ///
        ///[OMRON] 
        ///%OMRON_CDC%=Reader, USB\VID_0590&amp;PID_00CA
        ///
        ///;[Reader_Install.NTx86] 
        ///;Windows200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OMRON_X64_INF {
            get {
                return ResourceManager.GetString("OMRON_X64_INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OMRON_X86_CAT {
            get {
                object obj = ResourceManager.GetObject("OMRON_X86_CAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Setup File for Windows XP/2000
        ///; Copyright 2004-2005
        ///;
        ///; $Id: usbfCdcAcm.inf,v 1.5 2012/08/17 08:23:06 h-kita Exp $
        ///;
        ///; Ver:	1.01
        ///; Last Modify:	2005/Sep/09
        ///; Ver:	1.00
        ///; Last Modify:	2004/Jul/09
        ///
        ///[Version]
        ///LayoutFile=layout.inf
        ///Signature=&quot;$CHICAGO$&quot;
        ///Class=Ports
        ///ClassGuid={4D36E978-E325-11CE-BFC1-08002BE10318}
        ///Provider=%Company%
        ///DriverVer=11/22/2016,3.0.0.1 
        ///CatalogFile=HVC-P2_Win32.cat
        ///
        ///[DestinationDirs]
        ///DefaultDestDir=12
        ///
        ///[Manufacturer]
        ///%Company%=Models,NTamd64 
        ///
        ///[ClassInstall32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OMRON_X86_INF {
            get {
                return ResourceManager.GetString("OMRON_X86_INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenKeyboard {
            get {
                object obj = ResourceManager.GetObject("OpenKeyboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_12345_GDPR {
            get {
                object obj = ResourceManager.GetObject("SKIN_12345_GDPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SKIN_12345_ICO {
            get {
                object obj = ResourceManager.GetObject("SKIN_12345_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_12345_LOGO {
            get {
                object obj = ResourceManager.GetObject("SKIN_12345_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_12345_SPLASH {
            get {
                object obj = ResourceManager.GetObject("SKIN_12345_SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_12345_UPDATING {
            get {
                object obj = ResourceManager.GetObject("SKIN_12345_UPDATING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_34754_GDPR {
            get {
                object obj = ResourceManager.GetObject("SKIN_34754_GDPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SKIN_34754_ICO {
            get {
                object obj = ResourceManager.GetObject("SKIN_34754_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_34754_LOGO {
            get {
                object obj = ResourceManager.GetObject("SKIN_34754_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_34754_SPLASH {
            get {
                object obj = ResourceManager.GetObject("SKIN_34754_SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_34754_UPDATING {
            get {
                object obj = ResourceManager.GetObject("SKIN_34754_UPDATING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_55763_GDPR {
            get {
                object obj = ResourceManager.GetObject("SKIN_55763_GDPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SKIN_55763_ICO {
            get {
                object obj = ResourceManager.GetObject("SKIN_55763_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_55763_LOGO {
            get {
                object obj = ResourceManager.GetObject("SKIN_55763_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_55763_SPLASH {
            get {
                object obj = ResourceManager.GetObject("SKIN_55763_SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_55763_UPDATING {
            get {
                object obj = ResourceManager.GetObject("SKIN_55763_UPDATING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_76541_GDPR {
            get {
                object obj = ResourceManager.GetObject("SKIN_76541_GDPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SKIN_76541_ICO {
            get {
                object obj = ResourceManager.GetObject("SKIN_76541_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_76541_LOGO {
            get {
                object obj = ResourceManager.GetObject("SKIN_76541_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_76541_SPLASH {
            get {
                object obj = ResourceManager.GetObject("SKIN_76541_SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_76541_UPDATING {
            get {
                object obj = ResourceManager.GetObject("SKIN_76541_UPDATING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_DEFAULT_GDPR {
            get {
                object obj = ResourceManager.GetObject("SKIN_DEFAULT_GDPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SKIN_DEFAULT_ICO {
            get {
                object obj = ResourceManager.GetObject("SKIN_DEFAULT_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_DEFAULT_LOGO {
            get {
                object obj = ResourceManager.GetObject("SKIN_DEFAULT_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_DEFAULT_SPLASH {
            get {
                object obj = ResourceManager.GetObject("SKIN_DEFAULT_SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKIN_DEFAULT_UPDATING {
            get {
                object obj = ResourceManager.GetObject("SKIN_DEFAULT_UPDATING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
